# Generated by Django 6.0.5 on 2026-09-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=250, verbose_name='Başlıq (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=250, verbose_name='Başlıq (RU)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(default='Fərid Mahmudov', max_length=100)),
                ('short_summary', models.TextField(blank=True, verbose_name='Qısa xülasə (AZ)')),
                ('short_summary_en', models.TextField(blank=True, verbose_name='Qısa xülasə (EN)')),
                ('short_summary_ru', models.TextField(blank=True, verbose_name='Qısa xülasə (RU)')),
                ('content', models.TextField(verbose_name='Məzmun (AZ)')),
                ('content_en', models.TextField(blank=True, verbose_name='Məzmun (EN)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Məzmun (RU)')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('reading_time', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloq Yazısı',
                'verbose_name_plural': 'Bloq Yazıları',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Ad (RU)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(default='fa-globe-europe', max_length=50)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Əlaqə Mesajı',
                'verbose_name_plural': 'Əlaqə Mesajları',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Məkan adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Məkan adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Məkan adı (RU)')),
                ('country_code', models.CharField(blank=True, max_length=50)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('tours_count', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Məkan',
                'verbose_name_plural': 'Məkanlar',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Turun Baş Bələdçisi', max_length=100, verbose_name='Vəzifə (AZ)')),
                ('role_en', models.CharField(blank=True, max_length=100, verbose_name='Vəzifə (EN)')),
                ('role_ru', models.CharField(blank=True, max_length=100, verbose_name='Vəzifə (RU)')),
                ('avatar', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Bələdçi',
                'verbose_name_plural': 'Bələdçilər',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Təsdiqlənmiş Səyahətçi', max_length=100, verbose_name='Vəzifə/Status (AZ)')),
                ('role_en', models.CharField(blank=True, max_length=100, verbose_name='Vəzifə/Status (EN)')),
                ('role_ru', models.CharField(blank=True, max_length=100, verbose_name='Vəzifə/Status (RU)')),
                ('text', models.TextField(verbose_name='Rəy mətni (AZ)')),
                ('text_en', models.TextField(blank=True, verbose_name='Rəy mətni (EN)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Rəy mətni (RU)')),
                ('avatar', models.CharField(blank=True, max_length=500)),
                ('rating', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Müştəri Rəyi',
                'verbose_name_plural': 'Müştəri Rəyləri',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='travel.blogpost')),
            ],
            options={
                'verbose_name': 'Şərh',
                'verbose_name_plural': 'Şərhlər',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='travel.category'),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Başlıq (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Başlıq (RU)')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('duration_nights', models.PositiveIntegerField(default=6)),
                ('group_size', models.CharField(default='Maks. 16 nəfər', max_length=50, verbose_name='Qrup ölçüsü (AZ)')),
                ('group_size_en', models.CharField(blank=True, max_length=50, verbose_name='Qrup ölçüsü (EN)')),
                ('group_size_ru', models.CharField(blank=True, max_length=50, verbose_name='Qrup ölçüsü (RU)')),
                ('guide_language', models.CharField(default='Azərbaycan & Rus', max_length=100, verbose_name='Bələdçi dili (AZ)')),
                ('guide_language_en', models.CharField(blank=True, max_length=100, verbose_name='Bələdçi dili (EN)')),
                ('guide_language_ru', models.CharField(blank=True, max_length=100, verbose_name='Bələdçi dili (RU)')),
                ('visa_support', models.CharField(default='Şengen (Tam Dəstək)', max_length=100, verbose_name='Viza dəstəyi (AZ)')),
                ('visa_support_en', models.CharField(blank=True, max_length=100, verbose_name='Viza dəstəyi (EN)')),
                ('visa_support_ru', models.CharField(blank=True, max_length=100, verbose_name='Viza dəstəyi (RU)')),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=45)),
                ('short_description', models.TextField(blank=True, verbose_name='Qısa məlumat (AZ)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Qısa məlumat (EN)')),
                ('short_description_ru', models.TextField(blank=True, verbose_name='Qısa məlumat (RU)')),
                ('description', models.TextField(blank=True, verbose_name='Ətraflı məlumat (AZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Ətraflı məlumat (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Ətraflı məlumat (RU)')),
                ('main_image', models.CharField(blank=True, max_length=500)),
                ('banner_image', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='travel.category')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='travel.destination')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='travel.guide')),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
            },
        ),
        migrations.CreateModel(
            name='TourExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Daxil deyil (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Daxil deyil (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Daxil deyil (RU)')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='travel.tour')),
            ],
            options={
                'verbose_name': 'Daxil olmayan xidmət',
                'verbose_name_plural': 'Daxil olmayanlar',
            },
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Daxildir (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Daxildir (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Daxildir (RU)')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='travel.tour')),
            ],
            options={
                'verbose_name': 'Daxil olan xidmət',
                'verbose_name_plural': 'Daxil olanlar',
            },
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200, verbose_name='Gün Başlığı (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Gün Başlığı (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Gün Başlığı (RU)')),
                ('description', models.TextField(verbose_name='Açıqlama (AZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıqlama (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Açıqlama (RU)')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='travel.tour')),
            ],
            options={
                'verbose_name': 'Günlük Proqram',
                'verbose_name_plural': 'Günlük Proqramlar',
                'ordering': ['day_number'],
            },
        ),
    ]
